STOCKS:
  - AAPL: Apple
  - FB: Facebook
  - YHOO: Yahoo
  - GOOGL: Google
  - MSFT: Microsoft
  - AMZN: Amazon
DATABASE_ENV:
  URI: mongodb://localhost/stock-watch
  DB: stock-watch
  COLLECTION: collection