# TODOS
STOCKS:
  - AAPL: Apple
  - FB: Facebook
  - YHOO: Yahoo
  - GOOGL: Google
  - MSFT: Microsoft
  - AMZN: Amazon
DATABASE_ENV:
  URI: mongodb://db/stock-watch
  DB: stock-watch
  COLLECTION: collection